pipeline:
  build:
    image: golang
    environment:
      - GOPATH=/drone
    commands:
      - go test -i badc0de.net/pkg/go-tibia/...  # install dependencies of tests
      - go test badc0de.net/pkg/go-tibia/...  # test *everything*


