pipeline:
  build:
    image: golang
    environment:
      - GOPATH=/drone
    commands:
      - go get badc0de.net/pkg/go-tibia  # fetch the empty root package, but also all the children
      - go test badc0de.net/pkg/go-tibia/...  # test *everything*


